// Les étampes proviennent de fichiers SVG FLATICON et FREESVGCLIPART (licence: /assets/stamps/emojis/ et https://freesvgclipart.com)
// Poly SVG : http://seekvectorlogo.com/polytechnique-montreal-vector-logo-svg/
// tspaint.svg: créé par l'équipe 201
export const enum Urls {
    Angry = 'assets/stamps/emojis/angry.svg',
    Angry1 = 'assets/stamps/emojis/angry-1.svg',
    Bored1 = 'assets/stamps/emojis/bored-1.svg',
    Bored2 = 'assets/stamps/emojis/bored-2.svg',
    Bored = 'assets/stamps/emojis/bored.svg',
    Confused = 'assets/stamps/emojis/confused.svg',
    Confused1 = 'assets/stamps/emojis/confused-1.svg',
    Crying = 'assets/stamps/emojis/crying.svg',
    Embarrassed = 'assets/stamps/emojis/embarrassed.svg',
    Emoticons = 'assets/stamps/emojis/emoticons.svg',
    Fire = 'assets/stamps/emojis/fire.svg',
    Happy = 'assets/stamps/emojis/happy.svg',
    Happy1 = 'assets/stamps/emojis/happy-1.svg',
    Happy2 = 'assets/stamps/emojis/happy-2.svg',
    Happy3 = 'assets/stamps/emojis/happy-3.svg',
    Happy4 = 'assets/stamps/emojis/happy-4.svg',
    Ill = 'assets/stamps/emojis/ill.svg',
    InLove = 'assets/stamps/emojis/in-love.svg',
    Kissing = 'assets/stamps/emojis/kissing.svg',
    Mad = 'assets/stamps/emojis/mad.svg',
    Nerd = 'assets/stamps/emojis/nerd.svg',
    Ninja = 'assets/stamps/emojis/ninja.svg',
    Quiet = 'assets/stamps/emojis/quiet.svg',
    Sad = 'assets/stamps/emojis/sad.svg',
    Secret = 'assets/stamps/emojis/secret.svg',
    Smart = 'assets/stamps/emojis/smart.svg',
    Smile = 'assets/stamps/emojis/smile.svg',
    Smiling = 'assets/stamps/emojis/smiling.svg',
    Surprised1 = 'assets/stamps/emojis/surprised-1.svg',
    Surprised = 'assets/stamps/emojis/surprised.svg',
    Suspicious = 'assets/stamps/emojis/suspicious.svg',
    Suspicious1 = 'assets/stamps/emojis/suspicious-1.svg',
    TongueOut1 = 'assets/stamps/emojis/tongue-out-1.svg',
    TongueOut = 'assets/stamps/emojis/tongue-out.svg',
    Unhappy = 'assets/stamps/emojis/unhappy.svg',
    Wink = 'assets/stamps/emojis/wink.svg',

    SnowFlake = 'assets/stamps/others/snowflake.svg',
    Candy = 'assets/stamps/others/candy.svg',
    Dog = 'assets/stamps/others/dog.svg',
    Earth = 'assets/stamps/others/earth.svg',
    Star = 'assets/stamps/others/star.svg',
    Poly = 'assets/stamps/others/poly.svg',
    TSpaint = 'assets/stamps/others/tspaint.svg',
    Heart = 'assets/stamps/others/heart.svg',
    Car = 'assets/stamps/others/baby-car.svg',
}

export const URLS_EMOJIS = [
    Urls.Fire,
    Urls.Happy,
    Urls.Happy1,
    Urls.Happy2,
    Urls.Happy3,
    Urls.Happy4,
    Urls.InLove,
    Urls.Kissing,
    Urls.Nerd,
    Urls.Quiet,
    Urls.Ninja,
    Urls.Smile,
    Urls.Smiling,
    Urls.Secret,
    Urls.Smart,
    Urls.Sad,
    Urls.Bored,
    Urls.Bored1,
    Urls.Bored2,
    Urls.Ill,
    Urls.Embarrassed,
    Urls.Emoticons,
    Urls.Confused,
    Urls.Confused1,
    Urls.Surprised,
    Urls.Surprised1,
    Urls.Suspicious,
    Urls.Suspicious1,
    Urls.TongueOut1,
    Urls.TongueOut1,
    Urls.Unhappy,
    Urls.Wink,
    Urls.Angry,
    Urls.Angry1,
    Urls.Crying,
    Urls.Mad,
];

export const URLS_OTHERS = [Urls.SnowFlake, Urls.Candy, Urls.Dog, Urls.Earth, Urls.Star, Urls.Poly, Urls.TSpaint, Urls.Heart, Urls.Car];
